# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-01 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_inventory_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktails',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
