# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-02 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_auto_20170301_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktails',
            name='image',
            field=models.FileField(default=' ', upload_to=b''),
            preserve_default=False,
        ),
    ]
